### ISSUE TITLE
UX Test - Edit dish dialog - 5 second test

### ISSUE THREAD

**Issue by OwendB1** [DirkLemmen/Researches#5]
Have a look at the image for 5 seconds. After having a look at the image answer the following questions in a comment: 
- What is the purpose of the element?
- Did the design appear trustworthy?
- What was your impression of the design?
- What grabbed your attention?
- What words or sentences can you recall?

<image src="https://i.postimg.cc/63PDs6KX/image.png"/>

**Comment by rikleemans** [comment]
1: The purpose is clear that the element is editable with the given inputs
2: The design seems trustworthy
3: Dish image looks a little standard maybe add a little bit more styling
4: There is a choice for different languages
5: choose image button is not fully centered
